'use client'
import { Roboto } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import Navbar from "./_navbar/page";
import { Container, ThemeProvider } from "@mui/material";
import theme from "@/styles/theme";
import { Provider } from "react-redux";
import { store } from "./_redux/store";
import { Toaster } from 'react-hot-toast'

// export const metadata: Metadata = {
//   title: "Circle App",
//   description: "Generated by create next app",
// };

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700']
})

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body style={{ fontFamily: roboto.style.fontFamily }}>
        <Provider store={store}>
          <AppRouterCacheProvider>
            <Container maxWidth='sm' sx={{mt: 10}}>
              <ThemeProvider theme={theme}>
                <Navbar />
                {children}
                <Toaster />
              </ThemeProvider>
            </Container>
          </AppRouterCacheProvider>
        </Provider>
      </body>
    </html >
  );
}
